import { Weapon, LootItem, SectorMission } from '../types';

export const WEAPONS: Record<string, Weapon> = {
  pistol: {
    id: 'pistol',
    name: 'Tactical 9mm',
    type: 'Pistol',
    damage: 28,
    fireRate: 4.5,
    range: 520,
    spread: 0.05,
    bulletsPerShot: 1,
    magSize: 12,
    reloadTime: 1.2,
    bulletSpeed: 750,
    color: '#38bdf8', // bright cyan
    price: 0,
    unlocked: true,
    description: 'Reliable sidearm with suppressor. High precision and fast handling.',
  },
  smg: {
    id: 'smg',
    name: 'Vector-9 SMG',
    type: 'Submachine Gun',
    damage: 20,
    fireRate: 9.5,
    range: 460,
    spread: 0.12,
    bulletsPerShot: 1,
    magSize: 30,
    reloadTime: 1.4,
    bulletSpeed: 800,
    color: '#fbbf24', // amber/gold
    price: 1800,
    unlocked: false,
    description: 'Rapid-firing tactical SMG that shreds light armored patrols in close quarters.',
  },
  shotgun: {
    id: 'shotgun',
    name: 'Breacher 12G',
    type: 'Shotgun',
    damage: 18, // 18 x 5 = 90 total max burst!
    fireRate: 1.8,
    range: 360,
    spread: 0.22,
    bulletsPerShot: 5,
    magSize: 8,
    reloadTime: 1.8,
    bulletSpeed: 680,
    color: '#f87171', // red-orange
    price: 3200,
    unlocked: false,
    description: 'Heavy tactical pump shotgun. Fires a devastating 5-pellet spread at close range.',
  },
  rifle: {
    id: 'rifle',
    name: 'M4-Tactical AR',
    type: 'Assault Rifle',
    damage: 38,
    fireRate: 6.0,
    range: 650,
    spread: 0.04,
    bulletsPerShot: 1,
    magSize: 25,
    reloadTime: 1.6,
    bulletSpeed: 950,
    color: '#4ade80', // neon green
    price: 5500,
    unlocked: false,
    description: 'Military-spec assault rifle with superior range, armor penetration and stopping power.',
  },
  plasma: {
    id: 'plasma',
    name: 'Ion Plasma Carbine',
    type: 'Energy Weapon',
    damage: 55,
    fireRate: 3.5,
    range: 700,
    spread: 0.02,
    bulletsPerShot: 1,
    magSize: 18,
    reloadTime: 1.7,
    bulletSpeed: 900,
    color: '#c084fc', // purple neon
    price: 9000,
    unlocked: false,
    description: 'Experimental black-ops blaster firing ionized plasma bolts that melt armored foes.',
  },
  ak47: {
    id: 'ak47',
    name: 'AK47 Draco',
    type: 'Rifle de Asalto',
    damage: 44,
    fireRate: 6.8,
    range: 670,
    spread: 0.045,
    bulletsPerShot: 1,
    magSize: 30,
    reloadTime: 1.5,
    bulletSpeed: 980,
    color: '#f97316', // flaming orange
    price: 4800,
    unlocked: true,
    description: 'El legendario fusil de Free Fire. Gran poder de impacto, penetración de blindaje y ráfagas devastadoras.',
  },
  mp40: {
    id: 'mp40',
    name: 'MP40 Cobra',
    type: 'Subfusil SMG',
    damage: 23,
    fireRate: 13.0,
    range: 430,
    spread: 0.11,
    bulletsPerShot: 1,
    magSize: 32,
    reloadTime: 1.3,
    bulletSpeed: 880,
    color: '#eab308', // electric gold
    price: 4200,
    unlocked: true,
    description: 'La reina del combate cuerpo a cuerpo en Free Fire. Cadencia de tiro ultrasónica capaz de derretir robots.',
  },
  m1014: {
    id: 'm1014',
    name: 'M1014 Apocalipsis',
    type: 'Escopeta',
    damage: 24, // 24 * 6 = 144 max damage!
    fireRate: 2.1,
    range: 350,
    spread: 0.24,
    bulletsPerShot: 6,
    magSize: 6,
    reloadTime: 1.8,
    bulletSpeed: 720,
    color: '#ef4444', // crimson red
    price: 5200,
    unlocked: true,
    description: 'Escopeta táctica semiautomática. Destroza escudos y armaduras enemigas a corta distancia.',
  },
  awm: {
    id: 'awm',
    name: 'AWM Francotirador',
    type: 'Rifle de Precisión',
    damage: 175,
    fireRate: 0.9,
    range: 950,
    spread: 0.01,
    bulletsPerShot: 1,
    magSize: 5,
    reloadTime: 2.2,
    bulletSpeed: 1300,
    color: '#06b6d4', // neon cyan sniper tracer
    price: 8500,
    unlocked: true,
    description: 'El rifle francotirador más temido. Un solo impacto certero elimina robots de combate al instante.',
  },
  katana: {
    id: 'katana',
    name: 'Katana Samurai',
    type: 'Arma Cuerpo a Cuerpo',
    damage: 85,
    fireRate: 2.4,
    range: 90,
    spread: 0.35,
    bulletsPerShot: 1,
    magSize: 999,
    reloadTime: 0.1,
    bulletSpeed: 400,
    color: '#a855f7', // purple blade slash
    price: 2500,
    unlocked: true,
    isMelee: true,
    description: 'Katana militar afilada con filo molecular. Corta enemigos silenciosamente sin gastar munición.',
  },
};

export const LOOT_CATALOG: LootItem[] = [
  {
    id: 'pared_gloo',
    name: 'Granada Pared Gloo',
    rarity: 'rare',
    value: 600,
    icon: '🧊',
    category: 'tactical',
    description: '¡Famoso Muro de Hielo de Free Fire! Despliega una barrera protectora instantánea contra balas.',
    usable: true,
    glooWallCount: 1,
  },
  {
    id: 'chaleco_lvl2',
    name: 'Chaleco Táctico Nivel 2',
    rarity: 'rare',
    value: 800,
    icon: '🛡️',
    category: 'armor',
    description: 'Chaleco antibalas reforzado. Otorga +75 de escudo que absorbe daño antes de tu salud.',
    usable: true,
    shieldRestore: 75,
  },
  {
    id: 'chaleco_lvl3',
    name: 'Chaleco Militar Nivel 3',
    rarity: 'epic',
    value: 1500,
    icon: '🦺',
    category: 'armor',
    description: 'Blindaje balístico de nanopolímero. Otorga +120 de escudo de absorción máxima.',
    usable: true,
    shieldRestore: 120,
  },
  {
    id: 'placa_blindaje',
    name: 'Reparador de Blindaje',
    rarity: 'uncommon',
    value: 380,
    icon: '⚙️',
    category: 'armor',
    description: 'Kit de placas cerámicas. Restaura instantáneamente +50 de escudo a tu chaleco.',
    usable: true,
    shieldRestore: 50,
  },
  {
    id: 'rusted_watch',
    name: 'Rusted Watch',
    rarity: 'common',
    value: 180,
    icon: '⌚',
    category: 'valuable',
    description: 'Old industrial timepiece salvaged from maintenance lockers.',
  },
  {
    id: 'medkit',
    name: 'Medkit',
    rarity: 'uncommon',
    value: 350,
    icon: '🩹',
    category: 'medical',
    description: 'Military emergency trauma kit. Can be used in-combat to heal +50 HP!',
    usable: true,
  },
  {
    id: 'data_chip',
    name: 'Data Chip',
    rarity: 'rare',
    value: 650,
    icon: '💾',
    category: 'intel',
    description: 'Encrypted storage drive containing facility security logs.',
  },
  {
    id: 'cyber_battery',
    name: 'Plasma Cell',
    rarity: 'uncommon',
    value: 420,
    icon: '🔋',
    category: 'tech',
    description: 'Overcharged ionic battery cell from laboratory machinery.',
  },
  {
    id: 'encrypted_drive',
    name: 'Encrypted Drive',
    rarity: 'rare',
    value: 950,
    icon: '📁',
    category: 'intel',
    description: 'Classified corporate weapon blueprint partition.',
  },
  {
    id: 'nano_stim',
    name: 'Nano Stim',
    rarity: 'rare',
    value: 500,
    icon: '💉',
    category: 'medical',
    description: 'Adrenaline booster. Restores 35 HP and grants temporary burst speed!',
    usable: true,
  },
  {
    id: 'gold_ingot',
    name: 'Gold Ingot',
    rarity: 'epic',
    value: 1850,
    icon: '🧈',
    category: 'valuable',
    description: 'Smuggled bullion stamped with black market insignia.',
  },
  {
    id: 'neural_core',
    name: 'Neural Core',
    rarity: 'legendary',
    value: 3200,
    icon: '🧠',
    category: 'tech',
    description: 'Self-aware AI coprocessor recovered from high-security vault.',
  },
];

export const SECTOR_MISSIONS: SectorMission[] = [
  {
    id: 'sector_warehouse',
    name: 'Warehouse Sector 07',
    sectorCode: 'SEC-07',
    difficulty: 'Standard',
    description: 'An abandoned industrial logistics warehouse overrun by scavenger syndicates. Moderate security.',
    lootMultiplier: 1.0,
    extractionTimeSec: 50,
    theme: 'warehouse',
    ambientColor: '#0b131f',
    unlocked: true,
  },
  {
    id: 'sector_biohazard',
    name: 'Bio-Research Complex',
    sectorCode: 'BIO-12',
    difficulty: 'Hostile',
    description: 'Hazardous underground chem-lab. Toxic barrels and well-equipped enforcers guard valuable plasma data.',
    lootMultiplier: 1.45,
    extractionTimeSec: 65,
    theme: 'biohazard',
    ambientColor: '#0a1a14',
    unlocked: true,
  },
  {
    id: 'sector_depot',
    name: 'Black Ops Armory Depot',
    sectorCode: 'DEP-99',
    difficulty: 'Extreme',
    description: 'Heavily fortified military bunker with elite armored mercenaries and top-secret neural cores.',
    lootMultiplier: 2.1,
    extractionTimeSec: 80,
    theme: 'military',
    ambientColor: '#1a0e14',
    unlocked: true,
  },
];
